server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: dubbo-springboot-demo-cousmer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848